# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoGUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(803, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.MplWidget = MplWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MplWidget.sizePolicy().hasHeightForWidth())
        self.MplWidget.setSizePolicy(sizePolicy)
        self.MplWidget.setObjectName("MplWidget")
        self.gridLayout.addWidget(self.MplWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSubplot = QtWidgets.QMenu(self.menubar)
        self.menuSubplot.setObjectName("menuSubplot")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGrafico1_SG = QtWidgets.QAction(MainWindow)
        self.actionGrafico1_SG.setCheckable(True)
        self.actionGrafico1_SG.setChecked(True)
        self.actionGrafico1_SG.setEnabled(True)
        self.actionGrafico1_SG.setObjectName("actionGrafico1_SG")
        self.actionGrafico2_SG = QtWidgets.QAction(MainWindow)
        self.actionGrafico2_SG.setCheckable(True)
        self.actionGrafico2_SG.setObjectName("actionGrafico2_SG")
        self.actionGrafico3_SG = QtWidgets.QAction(MainWindow)
        self.actionGrafico3_SG.setCheckable(True)
        self.actionGrafico3_SG.setObjectName("actionGrafico3_SG")
        self.actionGrafico1_T = QtWidgets.QAction(MainWindow)
        self.actionGrafico1_T.setCheckable(True)
        self.actionGrafico1_T.setChecked(True)
        self.actionGrafico1_T.setObjectName("actionGrafico1_T")
        self.actionGrafico2_T = QtWidgets.QAction(MainWindow)
        self.actionGrafico2_T.setCheckable(True)
        self.actionGrafico2_T.setObjectName("actionGrafico2_T")
        self.actionGrafico3_T = QtWidgets.QAction(MainWindow)
        self.actionGrafico3_T.setCheckable(True)
        self.actionGrafico3_T.setObjectName("actionGrafico3_T")
        self.actionGrafico1_A = QtWidgets.QAction(MainWindow)
        self.actionGrafico1_A.setCheckable(True)
        self.actionGrafico1_A.setChecked(True)
        self.actionGrafico1_A.setObjectName("actionGrafico1_A")
        self.actionGrafico2_A = QtWidgets.QAction(MainWindow)
        self.actionGrafico2_A.setCheckable(True)
        self.actionGrafico2_A.setObjectName("actionGrafico2_A")
        self.actionGrafico3_A = QtWidgets.QAction(MainWindow)
        self.actionGrafico3_A.setCheckable(True)
        self.actionGrafico3_A.setObjectName("actionGrafico3_A")
        self.actionAtivar = QtWidgets.QAction(MainWindow)
        self.actionAtivar.setCheckable(True)
        self.actionAtivar.setObjectName("actionAtivar")
        self.actionDesativar = QtWidgets.QAction(MainWindow)
        self.actionDesativar.setCheckable(True)
        self.actionDesativar.setChecked(True)
        self.actionDesativar.setObjectName("actionDesativar")
        self.actionDescartar_SG = QtWidgets.QAction(MainWindow)
        self.actionDescartar_SG.setCheckable(True)
        self.actionDescartar_SG.setObjectName("actionDescartar_SG")
        self.actionDescartar_T = QtWidgets.QAction(MainWindow)
        self.actionDescartar_T.setCheckable(True)
        self.actionDescartar_T.setObjectName("actionDescartar_T")
        self.actionDescartar_A = QtWidgets.QAction(MainWindow)
        self.actionDescartar_A.setCheckable(True)
        self.actionDescartar_A.setObjectName("actionDescartar_A")
        self.actionX_AXIS = QtWidgets.QAction(MainWindow)
        self.actionX_AXIS.setCheckable(True)
        self.actionX_AXIS.setChecked(True)
        self.actionX_AXIS.setObjectName("actionX_AXIS")
        self.actionY_AXIS = QtWidgets.QAction(MainWindow)
        self.actionY_AXIS.setCheckable(True)
        self.actionY_AXIS.setObjectName("actionY_AXIS")
        self.actionZ_AXIS = QtWidgets.QAction(MainWindow)
        self.actionZ_AXIS.setCheckable(True)
        self.actionZ_AXIS.setObjectName("actionZ_AXIS")
        self.actionPLOT2 = QtWidgets.QAction(MainWindow)
        self.actionPLOT2.setObjectName("actionPLOT2")
        self.actionPLOT3 = QtWidgets.QAction(MainWindow)
        self.actionPLOT3.setObjectName("actionPLOT3")
        self.actionplot_2 = QtWidgets.QAction(MainWindow)
        self.actionplot_2.setObjectName("actionplot_2")
        self.actionplot_3 = QtWidgets.QAction(MainWindow)
        self.actionplot_3.setObjectName("actionplot_3")
        self.actionPlot_2 = QtWidgets.QAction(MainWindow)
        self.actionPlot_2.setObjectName("actionPlot_2")
        self.actionPlot_3 = QtWidgets.QAction(MainWindow)
        self.actionPlot_3.setObjectName("actionPlot_3")
        self.actionDesconectar = QtWidgets.QAction(MainWindow)
        self.actionDesconectar.setObjectName("actionDesconectar")
        self.menuFile.addAction(self.actionDesconectar)
        self.menuSubplot.addAction(self.actionAtivar)
        self.menuSubplot.addSeparator()
        self.menuSubplot.addAction(self.actionPlot_2)
        self.menuSubplot.addAction(self.actionPlot_3)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSubplot.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSubplot.setTitle(_translate("MainWindow", "Subplot"))
        self.actionGrafico1_SG.setText(_translate("MainWindow", "Gráfico 1 (padrão)"))
        self.actionGrafico2_SG.setText(_translate("MainWindow", "Gráfico 2"))
        self.actionGrafico3_SG.setText(_translate("MainWindow", "Gráfico 3"))
        self.actionGrafico1_T.setText(_translate("MainWindow", "Gráfico 1 (padrão)"))
        self.actionGrafico2_T.setText(_translate("MainWindow", "Gráfico 2"))
        self.actionGrafico3_T.setText(_translate("MainWindow", "Gráfico 3"))
        self.actionGrafico1_A.setText(_translate("MainWindow", "Gráfico 1"))
        self.actionGrafico2_A.setText(_translate("MainWindow", "Gráfico 2 (padrão)"))
        self.actionGrafico3_A.setText(_translate("MainWindow", "Gráfico 3"))
        self.actionAtivar.setText(_translate("MainWindow", "Ativar"))
        self.actionDesativar.setText(_translate("MainWindow", "Desativar"))
        self.actionDescartar_SG.setText(_translate("MainWindow", "Descartar"))
        self.actionDescartar_T.setText(_translate("MainWindow", "Descartar"))
        self.actionDescartar_A.setText(_translate("MainWindow", "Descartar"))
        self.actionX_AXIS.setText(_translate("MainWindow", "X_AXIS"))
        self.actionY_AXIS.setText(_translate("MainWindow", "Y_AXIS"))
        self.actionZ_AXIS.setText(_translate("MainWindow", "Z_AXIS"))
        self.actionPLOT2.setText(_translate("MainWindow", "PLOT2"))
        self.actionPLOT3.setText(_translate("MainWindow", "PLOT3"))
        self.actionplot_2.setText(_translate("MainWindow", "plot_2"))
        self.actionplot_3.setText(_translate("MainWindow", "plot_3"))
        self.actionPlot_2.setText(_translate("MainWindow", "Plot_2"))
        self.actionPlot_3.setText(_translate("MainWindow", "Plot_3"))
        self.actionDesconectar.setText(_translate("MainWindow", "Desconectar"))


from mplwidget import MplWidget
