# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoIniciamento.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(542, 357)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(dialog)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(150, 40, 249, 25))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayoutWidget = QtWidgets.QWidget(dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 100, 141, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonCarregar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButtonCarregar.setFont(font)
        self.pushButtonCarregar.setObjectName("pushButtonCarregar")
        self.verticalLayout.addWidget(self.pushButtonCarregar)
        self.pushButtonDeletar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButtonDeletar.setFont(font)
        self.pushButtonDeletar.setObjectName("pushButtonDeletar")
        self.verticalLayout.addWidget(self.pushButtonDeletar)
        self.pushButtonConectar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButtonConectar.setFont(font)
        self.pushButtonConectar.setObjectName("pushButtonConectar")
        self.verticalLayout.addWidget(self.pushButtonConectar)
        self.pushButtonSair = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButtonSair.setFont(font)
        self.pushButtonSair.setObjectName("pushButtonSair")
        self.verticalLayout.addWidget(self.pushButtonSair)
        self.listWidgetCSV = QtWidgets.QListWidget(dialog)
        self.listWidgetCSV.setGeometry(QtCore.QRect(230, 181, 256, 111))
        self.listWidgetCSV.setObjectName("listWidgetCSV")
        self.pushButtonIniciar = QtWidgets.QPushButton(dialog)
        self.pushButtonIniciar.setGeometry(QtCore.QRect(320, 310, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.pushButtonIniciar.setFont(font)
        self.pushButtonIniciar.setObjectName("pushButtonIniciar")
        self.labelConectar = QtWidgets.QLabel(dialog)
        self.labelConectar.setGeometry(QtCore.QRect(70, 300, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelConectar.setFont(font)
        self.labelConectar.setText("")
        self.labelConectar.setObjectName("labelConectar")
        self.listWidget = QtWidgets.QListWidget(dialog)
        self.listWidget.setEnabled(False)
        self.listWidget.setGeometry(QtCore.QRect(230, 100, 256, 71))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Dialog"))
        self.label.setText(_translate("dialog", "Testes Interface"))
        self.pushButtonCarregar.setText(_translate("dialog", "Carregar (*.csv)"))
        self.pushButtonDeletar.setText(_translate("dialog", "Deletar (*.csv)"))
        self.pushButtonConectar.setText(_translate("dialog", "Conectar"))
        self.pushButtonSair.setText(_translate("dialog", "Sair"))
        self.pushButtonIniciar.setText(_translate("dialog", "Iniciar"))


